# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bb084fe0fca43571312311824f51552f9fd7c5bc74304da793c80393ac8abadf37a17150932dae4dc305d9b833a36de62ae602ffb68bf700c7ca4025268adf1

test:
  secret_key_base: 9279a8404d9d1ba055c02dac336a129f11195356d8dda2adb87f4379e36a7e565355b0cd143ee2e68bff33fb26358adeb1eb5fd56da8474230f965e088126e84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
